version: '3.8'

services:
  db_postgres:
    image: postgres:13.1
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./config/postgres/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    stdin_open: true
    tty: true
    networks:
      - my-network
    container_name: nest_app_db
  main_app:
    depends_on:
      - db_postgres
    build:
      context: ./microservices/app
    env_file: ./.env
    restart: unless-stopped
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment: 
      APP_PORT: $NODE_PORT
      DB_HOST: db_postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
    stdin_open: true
    tty: true
    networks:
      - my-network
    container_name: nest_app
networks:
  my-network:
